### ISSUE TITLE
Fix issue related to invalid data value

### ISSUE THREAD

**Issue by jpk96** [CHESSComputing/ChessDataManagement#39] opened 2023-10-18 13:45 UTC
@vkuznet

When submitting a record /nfs/chess/aux/metadata/cycles/2023-3/id1a3/ko-3759-a/lineup-1/7/All.json ID1A3, I ran into an error. 

{"error":"invalid data value for key=Detectors, type=list_str, multiple=true, value=[Other]","status":400}

ID1A3.json got recently updated to include "Other" in the Detectors key. I run into a similar error at id3a when submitting a record to reflect the most recent changes made to that schema (ID3A.json).

**Comment by vkuznet** [comment] 2023-10-18 14:52
Peter, even though I merged your recent PR I forgot to propagate it to lab server. Now it is done and according to CI/CD status the changes went through. I suggest that you try out again and either report that the issue is gone or confirm it still exists.

**Comment by jpk96** [comment] 2023-10-18 20:50
Thank you Valentin. I just submitted /nfs/chess/aux/metadata/cycles/2023-3/id1a3/ko-3759-a/lineup-1/33/All.json, which has "Detectors": ["Other"] worked on id1a3. I will verify that this also works on id3a.

**Comment by jpk96** [comment] 2023-10-20 13:09
@vkuznet: Submitting data from 1A3 using 3A schema will not work because each station has its own schema. Data from 3A do not have BeamMode. And it should work. After the latest change to the 3A schema, I haven't had the chance to test with a record from 3A. I should be able to do so at some point today, and report back once done.

**Comment by jpk96** [comment] 2023-10-20 17:57
@vkuznet: I tested with /nfs/chess/aux/metadata/cycles/2023-3/id3a/gustafson-1-a/test-1/2/All.json using ID3A.json schema, and submitting the record to the dev server appeared to be successful.

**Comment by vkuznet** [comment] 2023-10-20 18:04
ok, great, then I'll update prod server and close this ticket.

**Comment by vkuznet** [comment] 2023-10-20 18:13
production server has been upgraded, I'm closing this issue.

**Closed by vkuznet** 2023-10-20 18:13 UTC
